feeds:
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLieMNwf_9T.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLgL3MuErUi.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLfsCyTsWIk.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRL_yWUiBcWj.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRL_iZOkfGYE.rss"

settings:
  update_interval_minutes: 15
