feeds:
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLieMNwf_9T.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLgL3MuErUi.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLfsCyTsWIk.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRL_yWUiBcWj.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRReMTtVnX9z.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRAhg551kOSaRRfBozoi9si.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRAra4SE0wiaRRxrtPfWILD.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRA3KXO5oODaRRx7p718Fty.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBA71bkFsCaRRykjLEp1wj.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBFXKPZuqiaRRzfxyK9V7S.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBRNbusmVyaRRz2fr2FTYy.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBWHKPZuqjaRR1T0VKXnqS.rss"

settings:
  update_interval_minutes: 15
