feeds:
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLieMNwf_9T.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLgL3MuErUi.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRLfsCyTsWIk.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRL_yWUiBcWj.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRLdipyG1mESaRReMTtVnX9z.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRAhg551kOSaRRfBozoi9si.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRAra4SE0wiaRRxrtPfWILD.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRA3KXO5oODaRRx7p718Fty.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBA71bkFsCaRRykjLEp1wj.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBFXKPZuqiaRRzfxyK9V7S.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBRNbusmVyaRRz2fr2FTYy.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBWHKPZuqjaRR1T0VKXnqS.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRRBjSKpIqXyaRR3_rFxE9Zi.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSCG5NvSVmyaRSCMNCtC8qS.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSCfUO7vw3SaRSClrSUIqQD.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSCuuEkaH8iaRSCycpEiAkC.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSDC4EhEyMiaRSDGxYihzVi.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSDS7eNxNbiaRSDWL1M4gNE.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSDdBYihzVjaRSDhTgWf7hi.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSDqrh1_rrSaRSDtwA_dS3z.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSD2Q6z4R6SaRSD5yC9ubES.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSEBHVLTS0yaRSEFXW0uKZy.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSEMb1M4gNFaRSEPZVvBpWC.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSEWzh0FKvyaRSEZJWQTr5T.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSEe5VvBpWDaRSEvlXjWJyS.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSE7DgWf7hjaRSE-3OeWnYz.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSFYHVLTS0zaRSFHQA_dS31.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSFrO1rkazSaRSFuCwu8M2y.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSF5eYwBLpDaRSF9DzGllty.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSGJywu8M2zaRSGNfuVp32i.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSGZnW0uKZzaRSGcpu8Rvbz.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSGqXOeWnY0aRSGtDh0FKvz.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSG7cYTOpWiaRSG-3YmyR4i.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSHNLMwp9cDaRSHQeIt0bsC.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSHZ2HOidvyaRSHdDh0FKv1.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSHmyC9ubETaRSHp8M11NVy.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSJbD3gWs9CaRSJgAtBaUTj.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSJmoqpTJAiaRSJpitOONtS.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSJwRyGvL0yaRSJy1lAcUbi.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSJ7JBM1yyEaRSJ_NHrvKNi.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSKHjOdGMJCaRSKK9mPzp-i.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSKSHW0uKZ0aRSKVmKDZWmS.rss"
  - fetchrss_url: "https://fetchrss.com/feed/aRSKcEm7WoqCaRSKfkiEQXOi.rss"

settings:
  update_interval_minutes: 15
